---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: sidraut007/todo-frontend:4
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://localhost:8080/api/tasks" # assuming backend service is on port 8080 

        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  ports:
  - port: 80
    protocol: TCP
  type: ClusterIP
  selector:
   role: frontend